[versions]
plugin-android = "7.4.1"
plugin-maven = "0.22.0"
plugin-composeMultiplatform = "1.3.1"
voyager = "1.0.0-rc04"
coroutines = "1.6.4"
appCompat = "1.5.1"
composeActivity = "1.6.1"

kotlin = "1.8.10"
uiAndroid = "1.5.4"

[libraries]
plugin-android = { module = "com.android.tools.build:gradle", version.ref = "plugin-android" }
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-maven = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "plugin-maven" }
plugin-composeMultiplatform = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "plugin-composeMultiplatform" }

coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
appCompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompat" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "composeActivity" }

voyager-navigator = { module = "cafe.adriel.voyager:voyager-navigator", version.ref = "voyager" }
voyager-transitions = { module = "cafe.adriel.voyager:voyager-transitions", version.ref = "voyager" }
ui-android = { group = "androidx.compose.ui", name = "ui-android", version.ref = "uiAndroid" }